//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tez.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbKnowMeBetterEntities : DbContext
    {
        public DbKnowMeBetterEntities()
            : base("name=DbKnowMeBetterEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tbl_Ziyaretci> Tbl_Ziyaretci { get; set; }
        public virtual DbSet<Tblİşveren> Tblİşveren { get; set; }
        public virtual DbSet<TblİşArayan> TblİşArayan { get; set; }
        public virtual DbSet<Tbl_Başvuranlar> Tbl_Başvuranlar { get; set; }
        public virtual DbSet<Tbl_İlan> Tbl_İlan { get; set; }
    }
}
