//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tez.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_İlan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_İlan()
        {
            this.Tbl_Başvuranlar = new HashSet<Tbl_Başvuranlar>();
            this.Tblİşveren = new HashSet<Tblİşveren>();
        }
    
        public int ID { get; set; }
        public string ilan_sahibi { get; set; }
        public string Acıklama { get; set; }
        public string Baslik { get; set; }
        public string Tarih { get; set; }
        public string Nitelikler { get; set; }
        public string Adres { get; set; }
        public string Pozisyon { get; set; }
        public string Departman { get; set; }
        public string CalismaSekli { get; set; }
        public string Tecrube { get; set; }
        public Nullable<int> Başvuru { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Başvuranlar> Tbl_Başvuranlar { get; set; }
        public virtual Tbl_Başvuranlar Tbl_Başvuranlar1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tblİşveren> Tblİşveren { get; set; }
    }
}
