//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tez.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Ziyaretci
    {
        public int ID { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string Mail { get; set; }
        public string Telefon { get; set; }
        public string Adres { get; set; }
        public string D_Tarihi { get; set; }
        public string Egitim { get; set; }
        public string Tecrube { get; set; }
        public string Sertifika { get; set; }
        public string Dil_Yetenek { get; set; }
        public string Hobiler { get; set; }
        public string Uyelik { get; set; }
        public string Sürücü_bel { get; set; }
        public string Fotograf { get; set; }
        public string Pc_yetenek { get; set; }
    }
}
