//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tez.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Başvuranlar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Başvuranlar()
        {
            this.Tbl_İlan1 = new HashSet<Tbl_İlan>();
        }
    
        public int ID { get; set; }
        public Nullable<int> İlan { get; set; }
        public Nullable<int> Başvuran_Ad { get; set; }
        public Nullable<int> Başvuran_Soyad { get; set; }
        public Nullable<int> Başvuran_KullanıcıAd { get; set; }
    
        public virtual Tbl_İlan Tbl_İlan { get; set; }
        public virtual TblİşArayan TblİşArayan { get; set; }
        public virtual TblİşArayan TblİşArayan1 { get; set; }
        public virtual TblİşArayan TblİşArayan2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_İlan> Tbl_İlan1 { get; set; }
    }
}
