//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tez.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tblİşveren
    {
        public int ID { get; set; }
        public string KullanıcıAd { get; set; }
        public string FirmaAd { get; set; }
        public string Mail { get; set; }
        public string Parola { get; set; }
        public string Hakkında { get; set; }
        public string Misyon { get; set; }
        public string Kuruluş { get; set; }
        public string İletişim { get; set; }
        public string Adres { get; set; }
        public Nullable<int> İlan { get; set; }
        public string ProfilFoto { get; set; }
        public string Sektör { get; set; }
    
        public virtual Tbl_İlan Tbl_İlan { get; set; }
    }
}
