//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tez.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblİşArayan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblİşArayan()
        {
            this.Tbl_Başvuranlar = new HashSet<Tbl_Başvuranlar>();
            this.Tbl_Başvuranlar1 = new HashSet<Tbl_Başvuranlar>();
            this.Tbl_Başvuranlar2 = new HashSet<Tbl_Başvuranlar>();
        }
    
        public int ID { get; set; }
        public string KullanıcıAdı { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string Mail { get; set; }
        public string Parola { get; set; }
        public string İletisim { get; set; }
        public string Adres { get; set; }
        public string D_Tarihi { get; set; }
        public string Egitim { get; set; }
        public string Tecrube { get; set; }
        public string Sertifika { get; set; }
        public string Uyelik { get; set; }
        public string Pc_yetenek { get; set; }
        public string Dil_yetenek { get; set; }
        public string Hobiler { get; set; }
        public string Surucu_bel { get; set; }
        public string Hakkında { get; set; }
        public string Hedefler { get; set; }
        public string ProfilFoto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Başvuranlar> Tbl_Başvuranlar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Başvuranlar> Tbl_Başvuranlar1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Başvuranlar> Tbl_Başvuranlar2 { get; set; }
    }
}
